---
roles:
  - name: stefangweichinger.ansible_rclone
    version: 0.2.2
  - name: geerlingguy.docker
    version: 7.4.7

collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 9.5.8
  - name: community.docker
    version: 4.6.0
  - name: vladgh.samba
    version: 3.4.0
